create extension if not exists pgcrypto with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  owner_user_id uuid not null references auth.users (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint organizations_name_not_blank check (btrim(name) <> ''),
  constraint organizations_slug_not_blank check (btrim(slug) <> '')
);

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null,
  status text not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint memberships_role_check check (role in ('owner', 'admin', 'member')),
  constraint memberships_status_check check (status in ('active', 'invited', 'suspended')),
  constraint memberships_unique_member unique (organization_id, user_id)
);

create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null unique references public.organizations (id) on delete cascade,
  provider text not null default 'stripe',
  provider_customer_id text,
  provider_subscription_id text unique,
  plan_key text not null default 'free',
  status text not null default 'inactive',
  billing_email text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint subscriptions_provider_check check (provider in ('stripe')),
  constraint subscriptions_status_check check (
    status in ('inactive', 'trialing', 'active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'unpaid')
  )
);

create table public.activity_logs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations (id) on delete cascade,
  actor_user_id uuid references auth.users (id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint activity_logs_action_not_blank check (btrim(action) <> ''),
  constraint activity_logs_entity_type_not_blank check (btrim(entity_type) <> '')
);

create index memberships_user_id_idx on public.memberships (user_id);
create index memberships_organization_id_idx on public.memberships (organization_id);
create index activity_logs_organization_id_idx on public.activity_logs (organization_id, created_at desc);
create index subscriptions_status_idx on public.subscriptions (status);

create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create trigger set_organizations_updated_at
before update on public.organizations
for each row
execute function public.set_updated_at();

create trigger set_memberships_updated_at
before update on public.memberships
for each row
execute function public.set_updated_at();

create trigger set_subscriptions_updated_at
before update on public.subscriptions
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update
    set email = excluded.email,
        updated_at = timezone('utc', now());

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function public.is_organization_member(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.memberships memberships
    where memberships.organization_id = p_organization_id
      and memberships.user_id = auth.uid()
      and memberships.status = 'active'
  );
$$;

create or replace function public.has_organization_role(p_organization_id uuid, p_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.memberships memberships
    where memberships.organization_id = p_organization_id
      and memberships.user_id = auth.uid()
      and memberships.status = 'active'
      and memberships.role = any (p_roles)
  );
$$;

create or replace function public.create_organization(p_name text, p_slug text default null)
returns public.organizations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_organization public.organizations;
  v_slug text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if p_name is null or btrim(p_name) = '' then
    raise exception 'Organization name is required';
  end if;

  v_slug := coalesce(nullif(lower(btrim(p_slug)), ''), lower(regexp_replace(btrim(p_name), '[^a-zA-Z0-9]+', '-', 'g')));
  v_slug := trim(both '-' from v_slug);

  if v_slug = '' then
    raise exception 'Organization slug is required';
  end if;

  insert into public.organizations (name, slug, owner_user_id)
  values (btrim(p_name), v_slug, auth.uid())
  returning * into v_organization;

  insert into public.memberships (organization_id, user_id, role, status)
  values (v_organization.id, auth.uid(), 'owner', 'active');

  insert into public.activity_logs (organization_id, actor_user_id, action, entity_type, entity_id)
  values (v_organization.id, auth.uid(), 'organization.created', 'organization', v_organization.id);

  return v_organization;
end;
$$;

revoke all on function public.create_organization(text, text) from public;
grant execute on function public.create_organization(text, text) to authenticated;

alter table public.profiles enable row level security;
alter table public.organizations enable row level security;
alter table public.memberships enable row level security;
alter table public.subscriptions enable row level security;
alter table public.activity_logs enable row level security;

create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (id = auth.uid());

create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (id = auth.uid());

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "organizations_select_for_members"
on public.organizations
for select
to authenticated
using (public.is_organization_member(id));

create policy "organizations_update_for_owner"
on public.organizations
for update
to authenticated
using (public.has_organization_role(id, array['owner']))
with check (public.has_organization_role(id, array['owner']));

create policy "organizations_delete_for_owner"
on public.organizations
for delete
to authenticated
using (public.has_organization_role(id, array['owner']));

create policy "memberships_select_for_members"
on public.memberships
for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_organization_member(organization_id)
);

create policy "memberships_insert_for_org_admins"
on public.memberships
for insert
to authenticated
with check (public.has_organization_role(organization_id, array['owner', 'admin']));

create policy "memberships_update_for_org_admins"
on public.memberships
for update
to authenticated
using (public.has_organization_role(organization_id, array['owner', 'admin']))
with check (public.has_organization_role(organization_id, array['owner', 'admin']));

create policy "memberships_delete_for_org_admins"
on public.memberships
for delete
to authenticated
using (public.has_organization_role(organization_id, array['owner', 'admin']));

create policy "subscriptions_select_for_org_admins"
on public.subscriptions
for select
to authenticated
using (public.has_organization_role(organization_id, array['owner', 'admin']));

create policy "subscriptions_insert_for_org_admins"
on public.subscriptions
for insert
to authenticated
with check (public.has_organization_role(organization_id, array['owner', 'admin']));

create policy "subscriptions_update_for_org_admins"
on public.subscriptions
for update
to authenticated
using (public.has_organization_role(organization_id, array['owner', 'admin']))
with check (public.has_organization_role(organization_id, array['owner', 'admin']));

create policy "subscriptions_delete_for_org_owners"
on public.subscriptions
for delete
to authenticated
using (public.has_organization_role(organization_id, array['owner']));

create policy "activity_logs_select_for_members"
on public.activity_logs
for select
to authenticated
using (public.is_organization_member(organization_id));

create policy "activity_logs_insert_for_members"
on public.activity_logs
for insert
to authenticated
with check (
  public.is_organization_member(organization_id)
  and coalesce(actor_user_id, auth.uid()) = auth.uid()
);
